### ISSUE TITLE
Can this module be called from action-gh-pages and other similar actions?

### ISSUE THREAD

**Issue by elsatch** [peaceiris/hugo-mod-mermaidjs#1]
I have just discovered this repository and tried to add it to my Hugo site. It is hosted here on GitHub and I am using action-gh-pages to construct it.

I am using the geeky-hugo theme that uses toml files for configuration, so I tried to adapt the yaml format in the documentation. My modules section on config/_default/config.toml looks like this:

```toml
############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"
[[module.imports]]
path = "github.com/peaceiris/hugo-mod-mermaidjs"
```

As I push this change into the repository, I am getting an error in the action log:
```console
Error: module "github.com/peaceiris/hugo-mod-mermaidjs" not found; either add it as a Hugo Module or store it in "/home/runner/work/elsatch.github.io/elsatch.github.io/themes".: module does not exist
```

So I am wondering if is it possible to import these modules on the Github actions, or if module import is restricted in some way into this environment.

I have taken a look to the project docs, the Hugo documentation about modules, but there are not lots of examples on how to use these modules in Hugo.
